// Mocks generated by Mockito 5.4.0 from annotations
// in cleanarchitecture/integration_test/counter/counter_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cleanarchitecture/src/core/error/failure.dart' as _i5;
import 'package:cleanarchitecture/src/features/counter/domain/entities/counter_model.dart' as _i6;
import 'package:cleanarchitecture/src/features/counter/domain/usecases/decrement_counter_use_case.dart' as _i8;
import 'package:cleanarchitecture/src/features/counter/domain/usecases/get_counter_use_case.dart' as _i3;
import 'package:cleanarchitecture/src/features/counter/domain/usecases/increment_counter_use_case.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCounterUseCase extends _i1.Mock implements _i3.GetCounterUseCase {
  MockGetCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>.value(_FakeEither_0<_i5.Failure, _i6.CounterModel>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>);
}

/// A class which mocks [IncrementCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementCounterUseCase extends _i1.Mock implements _i7.IncrementCounterUseCase {
  MockIncrementCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>.value(_FakeEither_0<_i5.Failure, _i6.CounterModel>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>);
}

/// A class which mocks [DecrementCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecrementCounterUseCase extends _i1.Mock implements _i8.DecrementCounterUseCase {
  MockDecrementCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>.value(_FakeEither_0<_i5.Failure, _i6.CounterModel>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CounterModel>>);
}
